id: P007971
initial_creation_type: ocr
source_metadata:
  id: bdr:W16484
  title: དབུ་མ་ཟབ་དོན་གདམས་པའི་མིག་འབྱེད་གསེར་གྱི་ཐུར་མ།
  author: ''
  volumes:
    d1c8f9a6d91c427a9f25792543f2b15e:
      image_group_id: I1KG13436
      title: ''
      volume_number: 1
      total_pages: 470
    b6de243228e34fa5ba8c4c53a541981a:
      image_group_id: I1KG13437
      title: ''
      volume_number: 2
      total_pages: 346
ebook_metadata:
  title: དབུ་མ་ཟབ་དོན་གདམས་པའི་མིག་འབྱེད་གསེར་གྱི་ཐུར་མ།
  author: ''
  sku: P007971
  cover: cover.jpg
  layers:
  - pagination
