id: I2D29D0AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:52:49+00:00'
last_modified: '2022-06-09T08:09:22.394190+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W16484
  title: དབུ་མ་ཟབ་དོན་གདམས་པའི་མིག་འབྱེད་གསེར་གྱི་ཐུར་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6057':
      image_group_id: I1KG13436
      title: Volume 1 of dbu ma zab don gdams pa'i mig 'byed gser gyi thur ma/
      total_pages: 470
      order: 1
      base_file: 6057.txt
    1C61:
      image_group_id: I1KG13437
      title: Volume 2 of dbu ma zab don gdams pa'i mig 'byed gser gyi thur ma/
      total_pages: 346
      order: 2
      base_file: 1C61.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
